#!/usr/bin/env bash
if [[ "$1" == "-w" ]]; then
    arg_watch=isset
    shift
fi

set -xb
if [ -n "$arg_watch" ]; then
    if ! which reflect &> /dev/null; then
	   if ! go get github.com/cespare/reflex; then
		  echo "api: failed to install tool: reflect" >&2
		  exit 1
	   fi
    fi

    # -d none: Don't preprend output with anything
    # --start-service: Indicates program is expected to run for a long time
    # -g *.go: Watch for changes on any Go files
    reflex \
	   -d none \
	   --start-service \
	   -g *.go \
	   -- go run . "$@"
else
    go run . "$@"
fi
