#!/usr/bin/env bash
ctag=postgres:12-alpine
cname=dev-time-tracker-postgres
ccli="sudo podman"

POSTGRES_USER="dev-time-tracker"
POSTGRES_PASSWORD="dev-time-tracker"

function die() {
    echo "$0: $@" >&2
    exit 1
}

case "$1" in
    start)
	   if $ccli ps -a | grep "$cname" &> /dev/null; then
		  $ccli start "$cname"
	   else
		  $ccli run \
			   -d \
			   --name "$cname" \
			   -e POSTGRES_USER="$POSTGRES_USER" \
			   -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
			   --net host \
			   "$ctag"
	   fi
	   ;;
    stop) $ccli stop "$cname" ;;
    rm) $ccli rm -f "$cname" ;;
    *) die "unknown argument \"$1\", must be \"start\", \"stop\", \"rm\"" ;;
esac
