services:
  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./:/opt/time-tracker/
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 4001:4001
    volumes:
      - ./:/opt/time-tracker/
    restart: always